name: Publish Package

on: 
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with modules
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        run: |
          yarn
          yarn build
          yarn publish
        
